#!/usr/bin/env bash
set -euo pipefail

# Run from project root even if this script is launched from another folder.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

# This script runs all paper tables:
#   Table I-IV   : single-source transfer ASR, generated by sh/run_table1.sh
#                  and summarized by scripts/summarize_tables1_4_transfer.py
#   Table V-VIII : SV-FCA ablation, perceptual quality, runtime, defense evaluation
#
# Optional skip flags:
#   SKIP_TABLES1_4=1 bash sh/run_tables_1_8.sh
#   SKIP_TABLE5=1 SKIP_TABLE6=1 bash sh/run_tables_1_8.sh

echo "=========================================="
echo "[RUN] Table I-IV: Single-source transfer ASR"
echo "=========================================="
if [[ "${SKIP_TABLES1_4:-0}" != "1" ]]; then
  bash sh/run_table1.sh
else
  echo "[SKIP] Table I-IV"
fi

echo "=========================================="
echo "[RUN] Table V-VIII"
echo "=========================================="
bash sh/run_tables_5_8.sh


if [[ "${RUN_FIGURES:-0}" == "1" && "${SKIP_FIGURES:-0}" != "1" ]]; then
  echo "=========================================="
  echo "[RUN] Figures"
  echo "=========================================="
  bash sh/run_figures.sh
fi

echo "=========================================="
echo "[DONE] Finished Table I-VIII"
echo "Outputs:"
echo "  ${OUT_DIR:-./runs}/table1_single_source_transfer/table1_cnn_to_cnn.csv"
echo "  ${OUT_DIR:-./runs}/table1_single_source_transfer/table2_cnn_to_vit.csv"
echo "  ${OUT_DIR:-./runs}/table1_single_source_transfer/table3_vit_to_cnn.csv"
echo "  ${OUT_DIR:-./runs}/table1_single_source_transfer/table4_vit_to_vit.csv"
echo "  ${OUT_DIR:-./runs}/table5_prime/table5_prime.csv"
echo "  ${OUT_DIR:-./runs}/table6_quality/table6_quality.csv"
echo "  ${OUT_DIR:-./runs}/table7_runtime/table7_runtime.csv"
echo "  ${OUT_DIR:-./runs}/table8_defense/table8_defense.csv"
echo "=========================================="
